## 4.2 유니버셜 함수 : 배열의 각 원소를 빠르게 처리하는 함수


**ufunc** : ndarray 안에 있는 데이터 원소별로 연산을 수행하는 함수

* 하나 이상의 스칼라값을 받아서 하나 이상의 스칼라 결과값을 반환하는 간단한 함수를 고속으로 수행할 수 있는 벡터화된 래퍼 함수

많은 ufunc는 sqrt나 exp같은 간단한 변형을 전체 원소에 적용할 수 있다.

**→단항 유니버설 함수**

In [25]:
import numpy as np

In [26]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [28]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

**이항** 유니버설 함수 : add나 maximum처럼 2개의 인자를 취해서 단일 배열을 반환하는 함수

In [29]:
x = np.random.randn(8)
y = np.random.randn(8)

In [30]:
x

array([-0.52314389, -1.99474747, -0.45576066,  1.73909758,  0.45880913,
        0.58398629, -2.91465733,  0.76074678])

In [31]:
y

array([ 0.5967716 ,  0.71087809,  0.98252522,  0.02905718, -1.97298893,
       -0.70459463,  0.28851637, -0.77464715])

**`numpy.maximum`** 은 x와 y의 원소별로 가장 큰 값을 계산

In [32]:
np.maximum(x, y)

array([0.5967716 , 0.71087809, 0.98252522, 1.73909758, 0.45880913,
       0.58398629, 0.28851637, 0.76074678])

* modf  : 파이썬 내장 함수인 divmod의 벡터화 버전, 분수를 받아서 몫과 나머지를 함께 반환

In [33]:
arr = np.random.randn(7) * 5
arr

array([-0.89675003, -1.19229637,  3.19352847,  7.19470648,  1.61578056,
       -1.91433246,  1.61869896])

In [34]:
remainder, whole_part = np.modf(arr)

In [35]:
# 나머지 반환
remainder

array([-0.89675003, -0.19229637,  0.19352847,  0.19470648,  0.61578056,
       -0.91433246,  0.61869896])

In [36]:
# 몫 반환
whole_part

array([-0., -1.,  3.,  7.,  1., -1.,  1.])

In [37]:
arr

array([-0.89675003, -1.19229637,  3.19352847,  7.19470648,  1.61578056,
       -1.91433246,  1.61869896])

In [38]:
# np.sqrt : 제곱근 반환 arr ** 0.5
np.sqrt(arr)

<ipython-input-38-b3d874250e53>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan,        nan, 1.78704462, 2.682295  , 1.27113357,
              nan, 1.27228101])

In [39]:
np.sqrt(arr, arr)

<ipython-input-39-164954cb2c14>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([       nan,        nan, 1.78704462, 2.682295  , 1.27113357,
              nan, 1.27228101])

In [40]:
arr

array([       nan,        nan, 1.78704462, 2.682295  , 1.27113357,
              nan, 1.27228101])