## 4.5 선형대수

**선형대수** : 행렬의 곱셈, 분할, 행렬식 그리고 정사각 행렬 수학 같은 배열을 다루는 라이브러리

* 매트랩과 같은 언어와 다르게 두 개의 2차원 배열을 * 연산자로 곱하면 행렬 곱셈이 아니라 대응하는 각각의 원소의 곱 계산
* 행렬 곱셈은 배열 메서드이자 numpy 네임스페이스 안에 있는 dot 함수 이용하여 계산

In [2]:
import numpy as np

In [3]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [4]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [6]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

* x.dot(y)는 np.dot(x, y)와 같다

In [7]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

2차원 배열과 곱셈이 가능한 크기의 1차원 배열 간의 행렬 곱셈의 결과는 1차원 배열이다.

In [10]:
np.dot(x, np.ones(3))

array([ 6., 15.])

**@** : 행렬 곱셈을 수행하는 연산자

In [12]:
np.ones(3)

array([1., 1., 1.])

In [11]:
x @ np.ones(3)

array([ 6., 15.])

**numpy.linalg** : 행렬의 분할과 역향렬, 행렬식과 같은 것들 포함

In [14]:
from numpy.linalg  import inv, qr

In [15]:
X = np.random.randn(5, 5)

In [17]:
mat = X.T.dot(X)

In [24]:
mat

array([[ 5.26423074,  0.04600737, -1.48478531,  0.44958394, -2.3794843 ],
       [ 0.04600737,  2.36520171,  1.32860256, -1.86091473, -0.2925064 ],
       [-1.48478531,  1.32860256,  3.32583467, -2.56738091,  1.17154342],
       [ 0.44958394, -1.86091473, -2.56738091,  2.64522005,  0.09890121],
       [-2.3794843 , -0.2925064 ,  1.17154342,  0.09890121,  4.88345207]])

In [25]:
#역행렬
inv(mat)

array([[ 0.2749645 ,  0.03997983,  0.26529284,  0.23633861,  0.06794206],
       [ 0.03997983,  1.44058344,  1.23141812,  2.21060342, -0.23442022],
       [ 0.26529284,  1.23141812,  3.22882947,  3.97941485, -0.65216675],
       [ 0.23633861,  2.21060342,  3.97941485,  5.7861676 , -0.82428097],
       [ 0.06794206, -0.23442022, -0.65216675, -0.82428097,  0.39698592]])

In [19]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  1.12488724e-16,  6.38044132e-17,
        -4.90908839e-16,  1.50320428e-16],
       [ 1.57533116e-17,  1.00000000e+00, -7.99481534e-16,
         1.09007639e-15, -2.68393587e-16],
       [ 9.28284018e-19, -6.03320970e-16,  1.00000000e+00,
         1.41967997e-15, -1.01648526e-16],
       [-3.91113424e-17,  4.21669633e-16,  1.48174532e-15,
         1.00000000e+00,  4.98729980e-16],
       [ 1.19639436e-16, -1.68436605e-16,  6.36661444e-16,
         1.03052512e-16,  1.00000000e+00]])

In [20]:
q, r = qr(mat)

In [23]:
r

array([[-5.98188102,  0.29460674,  2.78093124, -1.17806119,  4.3221748 ],
       [ 0.        , -3.28987099, -3.3765842 ,  3.76798266,  0.64763159],
       [ 0.        ,  0.        , -1.96469024,  1.19868192, -1.36160346],
       [ 0.        ,  0.        ,  0.        , -0.4911057 , -3.04414983],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.86975354]])

**자주 사용하는 numpy.linalg 함수**

**diag** : 정사각 행렬의 대각/비대각 원소를 1차원 배열로 반환하거나, 1차원 배열을 대각선 원소로 하고 나머지는 0으로 채운 단위행렬을 반환

**dot** : 행렬 곱셈

**trace** :행렬의 대각선 원소의 합 계산

**det** : 행렬식 계산

**eig** : 정사각 행렬의 고윳값과 고유벡터 계산

**inv** : 정사각 행렬의 역행렬 계산

**pinv** : 정사각 행렬의 무어-펜로즈 유사역원 역행렬 구하기

**qr** :  QR 분해 계산

**svd** : 특잇값 분해(SVD) 계산

**solve** : A가 정사각 행렬일 때,Ax = b를 만족하는 x 구하기

**istsq** : Ax = b를 만족하는 최소제곱해 구하기
