### Numpy

Numpy : Numerical Python


---



**Numpy 기능**
1. ndarray : 빠른 배열 계산과 유연한 **브로드캐스팅** 기능
2.전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수
3. 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 적재된 파일을 다루는 도구
4. 선형대수, 난수 생성기, 푸리에 변환 기능
5. C, C++, 포트란으로 작성한 코드를 연결할 수 있는 C API


## 4.1 NumPy ndarray : 다차원 배열 객체

In [ ]:
import numpy as np

# 임의의 값을 생성
data = np.random.randn(2,3)

data


array([[-0.49620522,  1.53425792,  0.41840664],
       [-1.37480955, -0.69608001, -0.99091566]])

**산술 연산**

In [ ]:
data * 10

array([[ -4.9620522 ,  15.34257922,   4.18406645],
       [-13.74809553,  -6.96080005,  -9.9091566 ]])

In [ ]:
data + data

array([[-0.99241044,  3.06851584,  0.83681329],
       [-2.74961911, -1.39216001, -1.98183132]])

In [ ]:
# shape : 각 차원의 크기
data.shape

(2, 3)

In [ ]:
# dtype :  튜플과 배열에 저장된 자료형 알려줌
data.dtype

dtype('float64')

### 4.1.1 ndarray 생성하기

파이썬의 리스트는 변환하기 좋은 예

In [ ]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

같은 길이를 가지는 **리스트를 내포**하고 있는 순차 데이터는 **다차원 배열로 변환** 가능

In [ ]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# 속성 검사
arr2.ndim

2

In [ ]:
arr2.shape

(2, 4)

In [ ]:
# 자료형 확인
arr1.dtype

dtype('float64')

In [ ]:
arr2.dtype

dtype('int64')

np.array 함수의 종류

1. zeros : 0 이 들어 있는 배열 생성
2. ones :  1이 들어 있는 배열 생성
3. empty : 초기화되지 않은 배열 생성

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

arange : 파이썬의 range 함수의 배열 버전

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 4.1.2 ndarray의dtype

In [ ]:
arr1 = np.array([1, 2, 3], dtype = np.float64)
arr2 = np.array([1, 2, 3], dtype = np.int32)

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
arr2.dtype

dtype('int32')

astype : ndarray 배열의 dtype을 다른 형으로 명시적으로 변환

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [ ]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [ ]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [ ]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

**숫자 형식의 문자열**을 담고 있는 배열 -> astype 사용하여 숫자로 변환

In [ ]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [ ]:
int_array = np.arange(10)

In [ ]:
calibers = np.array([.22, .270, .357, .280, .44, .50], dtype = np.float64)

In [ ]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

dtype으로 사용할 수 있는 축약 코드

In [ ]:
empty_unit32 = np.empty(8, dtype = 'u4')
empty_unit32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

### 4.1.3 NumPy 배열의 산술 연산


**벡터화** : for문을 작성하지 않고 데이터를 일괄 처리할 수 있다.
* 같은 크기의 배열 간의 산술 연산은 배열의 각 원소 단위로 적용

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
arr + arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [ ]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

스칼라 인자가 포함된 산술 연산의 경우 배열 내의 모든 원소에 **스칼라 인자가 적용됨**

In [ ]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [ ]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

같은 크기를 가지는 배열 간의 비교 연산은 **불리언 배열을 반환**

In [ ]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [ ]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

**브로드캐스팅 broadcasting**

: 크기가 다른 배열 간의 연산

### 4.1.4 색인과 슬라이싱 기초

1차원 배열 : 표면적으로는 파이썬의 리스트와 유사하게 동작

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[5]

5

In [ ]:
arr[5:8]

array([5, 6, 7])

In [ ]:
arr[5:8] = 12

In [ ]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

arr[5:8] = 12 처럼 배열 조각에 스칼라 값을 대입하면 12가 선택 영역 전체로 전파(or 브로드캐스팅)된다.

* 리스트와의 중요한 차이점 : 배열 조각은 원본 배열의 뷰라는 점

→ 데이터는 복사되지 않고, 뷰에 대한 변경은 그대로 원본 배열에 반영된다.

In [ ]:
arr_slice = arr[5:8]
arr_slice


array([12, 12, 12])

arr_slice의 값을 변경하면 원래 배열인 arr의 값도 변경됨

In [ ]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

[:] 로 슬라이스를 하면 배열의 모든 값 할당

In [ ]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [ ]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d[2]

array([7, 8, 9])

In [ ]:
arr2d[0][2]

3

In [ ]:
arr2d[0, 2]

3

2 X 2 X 3 크기의 배열

In [ ]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# arr3d[0]은 2 X 3 크기의 배열
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#arr3d[0]에는 스칼라값과 배열 모두 대입 가능
old_values = arr3d[0].copy()
arr3d[0] = 42

In [ ]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d[1, 0]

array([7, 8, 9])

In [ ]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
x[0]

array([7, 8, 9])

**슬라이스 선택**

In [ ]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [ ]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [ ]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [ ]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### 4.1.5 불리언값으로 선택

중복된 이름이 포함된 배열이 있다고 가정. numpy.random 모듈에 있는 randn 함수를 사용하여 임이의 표준 정규 분포 데이터 생성

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [ ]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [ ]:
data

array([[ 1.67323194, -0.6802189 ,  1.39728975,  0.35245795],
       [-1.79995838, -0.37886632,  1.32325208, -1.18985923],
       [ 1.10569676,  0.37916829,  2.11911248, -0.61927728],
       [ 1.27122183, -0.25048998, -0.10162065, -0.29813495],
       [ 0.78941058, -1.7282758 , -1.30069299, -1.39113076],
       [ 0.33390829, -1.21362478, -0.03591778,  0.10295634],
       [-1.35470706,  0.09883774,  0.14777282, -0.49057815]])

In [ ]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

불리언 배열은 배열의 색인으로 사용 가능

In [ ]:
data[names == 'Bob']

array([[ 1.67323194, -0.6802189 ,  1.39728975,  0.35245795],
       [ 1.27122183, -0.25048998, -0.10162065, -0.29813495]])

불리언 배열은 반드시 색인하려는 축의 길이와 동일한 길이를 가져야 함.

In [ ]:
data[names == 'Bob', 2:]

array([[ 1.39728975,  0.35245795],
       [-0.10162065, -0.29813495]])

'Bob' 이 아닌 요소들을 선택하려면 != 연산자 사용 or ~를 사용해서 조건절을 부인하면 된다.

In [ ]:
names != 'Bpb'

array([ True,  True,  True,  True,  True,  True,  True])

In [ ]:
data[~(names == 'Bpb')]

array([[ 1.67323194, -0.6802189 ,  1.39728975,  0.35245795],
       [-1.79995838, -0.37886632,  1.32325208, -1.18985923],
       [ 1.10569676,  0.37916829,  2.11911248, -0.61927728],
       [ 1.27122183, -0.25048998, -0.10162065, -0.29813495],
       [ 0.78941058, -1.7282758 , -1.30069299, -1.39113076],
       [ 0.33390829, -1.21362478, -0.03591778,  0.10295634],
       [-1.35470706,  0.09883774,  0.14777282, -0.49057815]])

In [ ]:
cond = names == 'Bob'

In [ ]:
data[~cond]

array([[-1.79995838, -0.37886632,  1.32325208, -1.18985923],
       [ 1.10569676,  0.37916829,  2.11911248, -0.61927728],
       [ 0.78941058, -1.7282758 , -1.30069299, -1.39113076],
       [ 0.33390829, -1.21362478, -0.03591778,  0.10295634],
       [-1.35470706,  0.09883774,  0.14777282, -0.49057815]])

세 가지 이름 중에서 두 가지 이름을 선택하려면 **&(and) 나  |(or)** 같은 논리 연산자를 사용

In [ ]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [ ]:
data[mask]

array([[ 1.67323194, -0.6802189 ,  1.39728975,  0.35245795],
       [ 1.10569676,  0.37916829,  2.11911248, -0.61927728],
       [ 1.27122183, -0.25048998, -0.10162065, -0.29813495],
       [ 0.78941058, -1.7282758 , -1.30069299, -1.39113076]])

In [ ]:
data[data < 0] = 0
data

array([[1.67323194, 0.        , 1.39728975, 0.35245795],
       [0.        , 0.        , 1.32325208, 0.        ],
       [1.10569676, 0.37916829, 2.11911248, 0.        ],
       [1.27122183, 0.        , 0.        , 0.        ],
       [0.78941058, 0.        , 0.        , 0.        ],
       [0.33390829, 0.        , 0.        , 0.10295634],
       [0.        , 0.09883774, 0.14777282, 0.        ]])

In [ ]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 1.32325208, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.33390829, 0.        , 0.        , 0.10295634],
       [0.        , 0.09883774, 0.14777282, 0.        ]])

### 4.1.6 팬시 색인

**팬시 색인** fancy indexing

: 정수 배열을 사용한 색인 설명하기 위해 NumPy에서 차용한 단어

In [ ]:
arr = np.empty((8,4))

In [ ]:
for i in range(8):
    arr[i] = i

In [ ]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

특정한 순서로 로우 선택 시

: 원하는 순서가 명시된 정수가 담긴 ndarray나 리스트 넘기면 된다.

In [ ]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

색인으로 음수 사용 시 끝에서부터 로우 선택

In [ ]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [ ]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [ ]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [ ]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### 4.1.7 배열 전치와 축 바꾸기

In [ ]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
arr = np.random.randn(6, 3)
arr

array([[ 1.46758568, -1.3102451 , -0.78925236],
       [-0.65120791,  1.46256788, -0.32972101],
       [-0.97296048, -0.36587565, -2.34674138],
       [-0.41639414, -1.33269374, -0.82615332],
       [ 0.27543287,  0.33160898,  0.65551572],
       [ 1.26626666, -0.33305895, -0.33520754]])

In [ ]:
np.dot(arr.T, arr)

array([[ 5.37721017, -2.29482973,  1.43980193],
       [-2.29482973,  5.9866774 ,  2.84051835],
       [ 1.43980193,  2.84051835,  7.4634246 ]])

다차원 배열의 경우 transpose 메서드는 튜플로 축 번호를 받아서 치환

In [ ]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

swapaxes : 두 개의 축 번호를 받아서 배열 뒤바꿔줌

In [ ]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])